### ISSUE TITLE
incompatibility with react-grid-layout

### ISSUE THREAD

**Issue by vinej** [alsacreations/KNACSS#204]
I tried to use the knacss css with my react application, but I have an incompatibility with the react-grid-layout librairy because of the usage [class*="grid-"]'

I did the following modifications to correct the problem with my application
  line 907 and 923
  [class*="grid-"] {  **SOULD BE**  [class^="grid-"]

I think that the idea was to use a 'start with'  not a 'contains'

Could you do the correction if it was an error ?

Thanks

**Comment by raphaelgoetter** [comment]
Hello @vinej ,

Actually, the CSS selector is `[class*="grid-"]` which is very different from `[class="grid-"]` and means that the string "grid-" can be anywhere within the class name.

If I switch to  `[class^="grid-"]`, many designs will be broken just because the class will now have to start with this string.

The best solution would be to use the Sass version which provides a namespace in order to resolve conflicts : https://github.com/alsacreations/KNACSS/blob/master/sass/_config-variables.scss#L70

**Comment by vinej** [comment]
Thanks, I will try the SSAS version
